### ISSUE TITLE
An en passant capture which removes a pawn that is giving check is not recognized as a legal move

### ISSUE THREAD

**Issue by bennedik** [ryancookdev/canvas-chess#6]
For example in the position given by the following FEN:

4r1k1/7p/p3pQp1/3p2P1/1p1P1RK1/2P5/7q/8 b - - 

After Black moves 1..h5+, the en passant capture 2.gxh6 is not recognized as a legal move.

**Comment by ryancookdev** [comment]
Thanks for the fix!
