### ISSUE TITLE
CHESS.Board.move() does not handle moves with pawn promotions

### ISSUE THREAD

**Issue by bennedik** [ryancookdev/canvas-chess#7]
If you create a chessboard, and then call the move method with a move in standard algebraic notation, which is a pawn promotion, e.g. "e8=Q", the move is not handled correctly and the pawn is not promoted.

Looking at the source code, the $.LongNotation.getLongNotation method does not support pawn promotions, and the Board.model.move method doesn't either, however there seems to be support for pawn promotions in the  $.BoardMover.move method.

**Comment by ryancookdev** [comment]
Pawns will now auto-promote to Queen. This happens as soon as the pawn reaches the end of the board, so you don't have to pass "=Q" as part of the move. A future enhancement will allow for passing different pieces, eg. "=N" to promote to a knight.
